export const CHANGE_FOCUS = 'header/CHANGE_FOCUS'
export const CHANGE_BLUR = 'header/CHANGE_BLUR'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'